[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
solc_version = "0.8.15"
optimizer_runs = 1000000
remappings = [
    '/=src',
    'libraries/=src/libraries',
    'interfaces/=src/interfaces',
]
sparse_mode = true

[etherscan]
mainnet = { key = "${MAINNET_ETHERSCAN_KEY"}
polygon = { key = "${POLYGON_ETHERSCAN_KEY"}
optimism = { key = "${OPTIMISM_ETHERSCAN_KEY"}